mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.ListView.as_view(), name='top'),
    path('search/', views.ListView.as_view(), name='search'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

mysite/register/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
from django.conf import settings

SKILLS_CHOICES = (
    ('1', 'Webデザイナー'),
    ('2', 'PG(フロントサイド)'),
    ('3', 'PG(サーバーサイド)'),
    ('4', 'デザイナー'),
    ('5', 'フォトグラファー'),
    ('6', 'イラストレーター'),
    ('7', 'ライター'),
    ('8', 'ブロガー'),
    ('9', 'その他'),
)

AREAS_CHOICES = (
    ('1', 'オンライン'),
    ('2', '北海道'),
    ('3', '青森県'),
    ('4', '岩手県'),
    ('5', '宮城県'),
    ('6', '秋田県'),
    ('7', '山形県'),
    ('8', '福島県'),
    ('9', '茨城県'),
    ('10', '栃木県'),
    ('11', '群馬県'),
    ('12', '埼玉県'),
    ('13', '千葉県'),
    ('14', '東京都'),
    ('15', '神奈川県'),
    ('16', '新潟県'),
    ('17', '富山県'),
    ('18', '石川県'),
    ('19', '福井県'),
    ('20', '山梨県'),
    ('21', '長野県'),
    ('22', '岐阜県'),
    ('23', '静岡県'),
    ('24', '愛知県'),
    ('25', '三重県'),
    ('26', '滋賀県'),
    ('27', '京都府'),
    ('28', '大阪府'),
    ('29', '兵庫県'),
    ('30', '奈良県'),
    ('31', '和歌山県'),
    ('32', '鳥取県'),
    ('33', '島根県'),
    ('34', '岡山県'),
    ('35', '広島県'),
    ('36', '山口県'),
    ('37', '徳島県'),
    ('38', '香川県'),
    ('39', '愛媛県'),
    ('40', '高知県'),
    ('41', '福岡県'),
    ('42', '佐賀県'),
    ('43', '長崎県'),
    ('44', '熊本県'),
    ('45', '大分県'),
    ('46', '宮崎県'),
    ('47', '鹿児島県'),
    ('48', '沖縄県'),
    ('49', 'その他')
)

REQUESTS_CHOICES = (
    ('1', '応相談'),
    ('2', '無料'),
    ('3', '〜10,000円'),
    ('4', '10,000円〜'),
    ('5', '50,000円〜'),
    ('6', '100,000円〜'),
    ('7', '500,000円〜'),

)

GENDER_CHOICES = (
    ('1', '女性'),
    ('2', '男性'),
)

class Profile(models.Model):
    name = models.CharField(("ハンドルネーム"), max_length=255)
    phone = models.CharField("電話番号", max_length=255, blank=True)
    gender = models.CharField("性別", max_length=2, choices=GENDER_CHOICES, blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)



    def __str__(self):
        return self.name


class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('メールアドレス'), unique=True)
    first_name = models.CharField(_('名'), max_length=30, blank=True)
    last_name = models.CharField(_('姓'), max_length=150, blank=True)
    nick_name = models.CharField(_('ニックネーム'), max_length=50, blank=False)
    picture = models.ImageField(_('トップ画像'), upload_to='media/', blank=True)  # 画像はあとで解決する
    twitter = models.CharField(_('Twitter'), max_length=50, blank=True)
    instagram = models.CharField(_('Instagram'), max_length=50, blank=True)
    skill = models.CharField(_('スキル'), max_length=150, choices=SKILLS_CHOICES, blank=False)
    area = models.CharField(_('活動範囲'), max_length=150, choices=AREAS_CHOICES, blank=False)
    request_fee = models.CharField(_('依頼料'), max_length=150, choices=REQUESTS_CHOICES, blank=False)
    portfolio = models.CharField(_('ポートフォリオ'), max_length=500, blank=True)
    self_introduction = models.CharField(_('自己PR'), max_length=500, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.email



    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email

mysite/register/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, resolve_url
from django.template.loader import render_to_string
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, EmailChangeForm, ProfileForm
)
from django.urls import reverse_lazy



User = get_user_model()


class ListView(generic.ListView):
    model = User
    template_name = 'register/top.html'
    paginate_by = 8
    queryset = User.objects.order_by('-created_at')

    def get_queryset(self):
        result = super(ListView, self).get_queryset()
        query = self.request.GET.get('q')

        if query:
            result = User.objects.filter(Q(skill__icontains=query))

        return result


class SearchView(generic.ListView):
    model = User
    template_name = 'register/top.html'
    paginate_by = 8

    def get_queryset(self):
        result = super(ListView, self).get_queryset()
        query = self.request.GET.get('q')

        if query:
            result = User.objects.filter(Q(nick_name__icontains=query) | Q(self_introduction__icontains=query))

        return result

class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'register/login.html'

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or resolve_url('register:user_detail', pk=self.request.user.pk)


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    model = User
    template_name = 'register/top.html'
    paginate_by = 8
    queryset = User.objects.order_by('-created_at')

    def get_queryset(self):
        result = super(ListView, self).get_queryset()
        query = self.request.GET.get('q')

        if query:
            result = User.objects.filter(Q(skill__icontains=query))

        return result


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('register/mail_template/create/subject.txt', context)
        message = render_to_string('register/mail_template/create/message.txt', context)

        user.email_user(subject, message)
        return redirect('register:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'register/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'register/user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'register/user_form.html'

    def get_success_url(self):
        return resolve_url('register:user_detail', pk=self.kwargs['pk'])


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('register:password_change_done')
    template_name = 'register/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'register/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'register/mail_template/password_reset/subject.txt'
    email_template_name = 'register/mail_template/password_reset/message.txt'
    template_name = 'register/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('register:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'register/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('register:password_reset_complete')
    template_name = 'register/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'register/password_reset_complete.html'


class EmailChange(LoginRequiredMixin, generic.FormView):
    """メールアドレスの変更"""
    template_name = 'register/email_change_form.html'
    form_class = EmailChangeForm

    def form_valid(self, form):
        user = self.request.user
        new_email = form.cleaned_data['email']

        # URLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(new_email),
            'user': user,
        }

        subject = render_to_string('register/mail_template/email_change/subject.txt', context)
        message = render_to_string('register/mail_template/email_change/message.txt', context)
        send_mail(subject, message, None, [new_email])

        return redirect('register:email_change_done')


class EmailChangeDone(LoginRequiredMixin, generic.TemplateView):
    """メールアドレスの変更メールを送ったよ"""
    template_name = 'register/email_change_done.html'


class EmailChangeComplete(LoginRequiredMixin, generic.TemplateView):
    """リンクを踏んだ後に呼ばれるメアド変更ビュー"""
    template_name = 'register/email_change_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            new_email = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            User.objects.filter(email=new_email, is_active=False).delete()
            request.user.email = new_email
            request.user.save()
            return super().get(request, **kwargs)

def register_user(request):
    user_form = UserCreateForm(request.POST or None)
    profile_form = ProfileForm(request.POST or None)
    if request.method == "POST" and user_form.is_valid() and profile_form.is_valid():

        # Userモデルの処理。ログインできるようis_activeをTrueにし保存
        user = user_form.save(commit=False)
        user.is_active = True
        user.save()

        # Profileモデルの処理。↑のUserモデルと紐づけましょう。
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        return redirect("register:top")

    context = {
        "user_form": user_form,
        "profile_form": profile_form,
    }
    return render(request, 'register/user_create.html', context)

mysite/register/templates/register/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>会員登録サンプル</title>
</head>
<body>
<header>
  <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'register:top' %}">Freelanze</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_detail' user.pk %}">マイページ</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_update' user.pk %}">マイページの更新</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:logout' %}">ログアウト</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:password_change' %}">パスワードの変更</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:email_change' %}">メールアドレスの変更</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'register:login' %}">
            ようこそ、ゲスト！ログインはこちら
          </a>
          </li>
          {% endif %}
        </ul>
          <div class="btn-group">
              <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  スキルで絞り込む
              </button>
              <form class="form-inline my-2 my-lg-0" action="" method="get" accept-charset="utf-8">
                  <div class="dropdown-menu">
                      <button class="dropdown-item" type="submit" value="1" name="q">Webデザイナー</button>
                      <button class="dropdown-item" type="submit" value="2" name="q">PG(フロントサイド)</button>
                      <button class="dropdown-item" type="submit" value="3" name="q">PG（サーバーサイド）</button>
                      <button class="dropdown-item" type="submit" value="4" name="q">デザイナー</button>
                      <button class="dropdown-item" type="submit" value="5" name="q">フォトグラファー</button>
                      <button class="dropdown-item" type="submit" value="6" name="q">イラストレーター</button>
                      <button class="dropdown-item" type="submit" value="7" name="q">ライター</button>
                      <button class="dropdown-item" type="submit" value="8" name="q">ブロガー</button>
                    <button class="dropdown-item" type="submit" value="9" name="q">その他</button>
                  </div><!-- /.dropdown-menu -->
              </form>
          </div><!-- /.btn-group -->
          <form class="form-inline my-2 my-lg-0" action="/search" method="get" accept-charset="utf-8">
              <input type="search" class="form-control mr-sm-2" placeholder="キーワードで検索" name="q" aria-label="検索...">
              <button type="submit" class="btn btn-outline-info my-2 my-sm-0">検索</button>
          </form>
      </div>
      </div>
    </nav>
</header>
<main>
    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>
</main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

mysite/register/templates/register/email_change_complete.html
{% extends "register/base.html" %}
{% block content %}
<p>
    メールアドレスを変更しました。<br>
</p>
{% endblock %}

mysite/register/templates/register/email_change_form.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

mysite/register/templates/register/login.html
{% extends "register/base.html" %}
{% block content %}
<div class="row">
    <!-- 左側、ログインエリア -->
    <div class="card col-md-6">
        <div class="card-body">
            <form action="{% url 'register:login' %}" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
            </form>
        </div>
        <p align="center">または</p>
        <div class="card-body">
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-danger btn-lg btn-block" >Googleアカウントでログイン</a>
        </div>
    </div><!-- 左側、ログインエリアおわり -->

<!-- 右側、会員登録エリア -->
    <div class="card col-md-6">
        <div class="card-body">
            <a href="{% url 'register:user_create' %}" class="btn btn-success btn-lg btn-block" >会員登録</a><hr>
            <a href="{% url 'register:password_reset' %}" class="btn btn-success btn-lg btn-block" >パスワードを忘れた方</a>
        </div>
    </div><!-- 右側、会員登録エリアおわり -->
</div>


{% endblock %}

mysite/register/templates/register/password_change.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

mysite/register/templates/register/password_change_done.html
{% extends "register/base.html" %}
{% block content %}
<p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

mysite/register/templates/register/password_reset_complete.html
{% extends "register/base.html" %}
{% block content %}
<p>
    パスワード再設定を完了しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

mysite/register/templates/register/password_reset_confirm.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

mysite/register/templates/register/password_reset_done.html
{% extends "register/base.html" %}
{% block content %}
<p>
    パスワード再設定用のメールを送信しました。<br>
    メールに記載されているリンクから再設定を行ってください。
</p>
{% endblock %}

mysite/register/templates/register/user_create.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

mysite/register/templates/register/user_create_complete.html
{% extends "register/base.html" %}
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

mysite/register/templates/register/user_create_done.html
{% extends "register/base.html" %}
{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
</p>
{% endblock %}

mysite/register/templates/register/user_form.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg" >送信</button>
</form>
{% endblock %}